apiVersion: v1
kind: Service
metadata:
  name: gym-tracker
  labels:
    app: gym-tracker
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access is needed
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: gym-tracker
